/**
 * Database types. Will be regenerated by Phase 2.2 once migrations land.
 *
 *   pnpm supabase:types
 *
 * For now, an empty Database type so client/server helpers compile.
 */

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T] extends { Row: infer R } ? R : never;
