-- ============================================================================
-- Phase 2.3 · Auxiliary schema: access_grants, coupons + coupon_redemptions,
-- content_submissions, feedback. RLS at the bottom.
--
-- The coupon redemption flow uses an atomic
-- SELECT FOR UPDATE → INSERT pattern wrapped in a Server Action
-- transaction, so two browsers redeeming the same single_use code at
-- the same moment can't both succeed.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- access_grants — one row per (user, book) pair granted digital access
-- ---------------------------------------------------------------------------
create type public.access_source as enum (
  'order',           -- normal: bought via the website
  'amazon',          -- offline: bought on Amazon, manually granted by admin
  'manual',          -- admin granted for any other reason (review copy, etc.)
  'refund_revoked'   -- previously granted, then revoked after refund
);

create table public.access_grants (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  book_id uuid not null references public.books(id) on delete restrict,
  order_id uuid references public.orders(id) on delete set null,
  source public.access_source not null default 'order',
  revoked_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  -- One active grant per (user, book) at a time. If revoked + re-granted,
  -- delete the old row first.
  unique (user_id, book_id)
);

create index access_grants_user_id_idx on public.access_grants (user_id);
create index access_grants_book_id_idx on public.access_grants (book_id);

-- ---------------------------------------------------------------------------
-- coupons — global codes (student10/teacher10) + dynamic single-use vendor
-- codes generated by admin
-- ---------------------------------------------------------------------------
create type public.coupon_type as enum ('global', 'single_use');

create table public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  type public.coupon_type not null,
  discount_percent integer not null check (discount_percent between 1 and 100),
  -- For global codes: max_uses can be null (unlimited per user but capped
  -- one redemption per user_id, see coupon_redemptions). For single_use:
  -- max_uses is always 1.
  max_uses integer,
  uses_count integer not null default 0 check (uses_count >= 0),
  -- Optional: codes that only work on specific books / formats / curricula.
  applies_to_curriculum public.curriculum,
  applies_to_format public.book_format,
  excludes_amazon boolean not null default true,
  -- Optional expiry — null means no expiry.
  expires_at timestamptz,
  created_by uuid references public.users(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  -- single_use codes must have max_uses = 1.
  constraint single_use_max_uses_is_one
    check (type = 'global' or (type = 'single_use' and max_uses = 1))
);

create index coupons_code_idx on public.coupons (code);
create index coupons_type_idx on public.coupons (type);

-- ---------------------------------------------------------------------------
-- coupon_redemptions — append-only audit log of every redemption
--
-- The unique (coupon_id, user_id) index for global codes is what enforces
-- "one redemption per email" for student10/teacher10. Server Action wraps
-- the redemption flow in BEGIN; SELECT coupon FOR UPDATE; check uses_count;
-- INSERT redemption; UPDATE uses_count + 1; COMMIT.
-- ---------------------------------------------------------------------------
create table public.coupon_redemptions (
  id uuid primary key default gen_random_uuid(),
  coupon_id uuid not null references public.coupons(id) on delete restrict,
  user_id uuid not null references public.users(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  discount_paise integer not null check (discount_paise >= 0),
  redeemed_at timestamptz not null default now(),
  -- One redemption per (coupon, user) — this is what makes student10/teacher10
  -- one-per-email and what makes single_use vendor codes truly single-use.
  unique (coupon_id, user_id)
);

create index coupon_redemptions_coupon_id_idx on public.coupon_redemptions (coupon_id);
create index coupon_redemptions_user_id_idx on public.coupon_redemptions (user_id);

-- ---------------------------------------------------------------------------
-- content_submissions — Creative Corner (poems / stories / dramas)
--
-- Guest submissions allowed: user_id can be null, submitter_email is captured
-- for moderation contact. Moderation is admin-only via the status column.
-- ---------------------------------------------------------------------------
create type public.submission_kind as enum ('poem', 'story', 'drama', 'essay', 'other');
create type public.moderation_status as enum ('pending', 'approved', 'rejected');

create table public.content_submissions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete set null,
  submitter_name text not null,
  submitter_email text not null,
  kind public.submission_kind not null,
  title text not null,
  body text not null,
  status public.moderation_status not null default 'pending',
  moderator_notes text,
  moderated_by uuid references public.users(id) on delete set null,
  moderated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index content_submissions_status_idx on public.content_submissions (status);
create index content_submissions_created_at_idx on public.content_submissions (created_at desc);

create trigger content_submissions_set_updated_at
  before update on public.content_submissions
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- feedback — public feedback form, also accepts guest submissions
-- ---------------------------------------------------------------------------
create type public.feedback_kind as enum (
  'bug', 'feature_request', 'content_request', 'praise', 'other'
);

create table public.feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete set null,
  submitter_name text,
  submitter_email text,
  kind public.feedback_kind not null default 'other',
  body text not null,
  resolved boolean not null default false,
  resolved_by uuid references public.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create index feedback_resolved_idx on public.feedback (resolved);
create index feedback_created_at_idx on public.feedback (created_at desc);

-- ============================================================================
-- RLS
-- ============================================================================

alter table public.access_grants enable row level security;
alter table public.coupons enable row level security;
alter table public.coupon_redemptions enable row level security;
alter table public.content_submissions enable row level security;
alter table public.feedback enable row level security;

-- ---------------------------------------------------------------------------
-- access_grants — user reads own non-revoked; admin all
-- ---------------------------------------------------------------------------
create policy access_grants_owner_select on public.access_grants
  for select using (user_id = auth.uid() and revoked_at is null);

create policy access_grants_admin_all on public.access_grants
  for all using (public.is_admin())
  with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- coupons — code lookup at checkout needs anon select on a single code.
--
-- Policy: anyone can SELECT a coupon row IF they know the exact code AND
-- the row is non-expired. We rely on the app filtering by `code = ?`; the
-- RLS check just adds the expiry filter so expired codes are invisible.
-- Admin sees all rows.
-- ---------------------------------------------------------------------------
create policy coupons_anon_select_non_expired on public.coupons
  for select using (expires_at is null or expires_at > now());

create policy coupons_admin_all on public.coupons
  for all using (public.is_admin())
  with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- coupon_redemptions — user reads own redemptions; admin all
-- ---------------------------------------------------------------------------
create policy coupon_redemptions_owner_select on public.coupon_redemptions
  for select using (user_id = auth.uid());

create policy coupon_redemptions_admin_all on public.coupon_redemptions
  for all using (public.is_admin())
  with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- content_submissions — guest insert allowed; only approved are publicly
-- readable; admin sees all + moderates
-- ---------------------------------------------------------------------------
create policy content_submissions_public_select_approved on public.content_submissions
  for select using (status = 'approved');

create policy content_submissions_owner_select on public.content_submissions
  for select using (user_id is not null and user_id = auth.uid());

-- Anyone (including anon) can insert. Server Action validates fields
-- before letting this fire.
create policy content_submissions_anyone_insert on public.content_submissions
  for insert with check (true);

create policy content_submissions_admin_all on public.content_submissions
  for all using (public.is_admin())
  with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- feedback — guest insert allowed; only admin reads
-- ---------------------------------------------------------------------------
create policy feedback_anyone_insert on public.feedback
  for insert with check (true);

create policy feedback_admin_all on public.feedback
  for all using (public.is_admin())
  with check (public.is_admin());
